DELETE FROM book_shop.book_shop.genre;
DELETE FROM book_shop.genre_lang;

INSERT INTO book_shop.genre (id, name, ord) VALUES (0, 'Закон', 00);
INSERT INTO book_shop.genre (id, name, ord) VALUES (1, 'Приготовление еды', 10);
INSERT INTO book_shop.genre (id, name, ord) VALUES (2, 'Игры и развлечения', 20);
INSERT INTO book_shop.genre (id, name, ord) VALUES (3, 'Психология', 30);
INSERT INTO book_shop.genre (id, name, ord) VALUES (4, 'История', 40);
INSERT INTO book_shop.genre (id, name, ord) VALUES (5, 'Детская художественная литература', 50);
INSERT INTO book_shop.genre (id, name, ord) VALUES (6, 'Химия, Неорганическая', 60);
INSERT INTO book_shop.genre (id, name, ord) VALUES (7, 'Алгебра', 70);
INSERT INTO book_shop.genre (id, name, ord) VALUES (8, 'Дом', 80);
INSERT INTO book_shop.genre (id, name, ord) VALUES (9, 'Образование', 90);
INSERT INTO book_shop.genre (id, name, ord) VALUES (10, 'Дипломатические отношения', 100);
INSERT INTO book_shop.genre (id, name, ord) VALUES (11, 'Поэзия', 110);
INSERT INTO book_shop.genre (id, name, ord) VALUES (12, 'Электронные книги', 120);
INSERT INTO book_shop.genre (id, name, ord) VALUES (13, 'Архитектура', 130);
INSERT INTO book_shop.genre (id, name, ord) VALUES (14, 'Литературная критика', 140);
INSERT INTO book_shop.genre (id, name, ord) VALUES (15, 'Тело, Разум и Дух', 150);
INSERT INTO book_shop.genre (id, name, ord) VALUES (16, 'Здоровье и Фитнес', 160);
INSERT INTO book_shop.genre (id, name, ord) VALUES (17, 'Художественная литература для молодых людей', 170);
INSERT INTO book_shop.genre (id, name, ord) VALUES (18, 'Литературные сборники', 180);
INSERT INTO book_shop.genre (id, name, ord) VALUES (19, 'Обществознание', 190);
INSERT INTO book_shop.genre (id, name, ord) VALUES (20, 'Антиквариат и Предметы коллекционирования', 200);
INSERT INTO book_shop.genre (id, name, ord) VALUES (21, 'Диета', 210);
INSERT INTO book_shop.genre (id, name, ord) VALUES (22, 'Медицинский', 220);
INSERT INTO book_shop.genre (id, name, ord) VALUES (23, 'Сказки', 230);
INSERT INTO book_shop.genre (id, name, ord) VALUES (24, 'Философия', 240);
INSERT INTO book_shop.genre (id, name, ord) VALUES (25, 'Компьютеры', 250);
INSERT INTO book_shop.genre (id, name, ord) VALUES (26, 'Биография и автобиография', 260);
INSERT INTO book_shop.genre (id, name, ord) VALUES (27, 'Искусство', 270);
INSERT INTO book_shop.genre (id, name, ord) VALUES (28, 'Коррупция', 280);
INSERT INTO book_shop.genre (id, name, ord) VALUES (29, 'Металлы', 290);
INSERT INTO book_shop.genre (id, name, ord) VALUES (30, 'Наука', 300);
INSERT INTO book_shop.genre (id, name, ord) VALUES (31, 'Математика', 310);
INSERT INTO book_shop.genre (id, name, ord) VALUES (32, 'Детская литература', 320);
INSERT INTO book_shop.genre (id, name, ord) VALUES (33, 'Ортогональные многочлены', 330);
INSERT INTO book_shop.genre (id, name, ord) VALUES (34, 'Спорт и отдых', 340);
INSERT INTO book_shop.genre (id, name, ord) VALUES (35, 'Природа', 350);
INSERT INTO book_shop.genre (id, name, ord) VALUES (36, 'Ссылки', 360);
INSERT INTO book_shop.genre (id, name, ord) VALUES (37, 'Религия', 370);
INSERT INTO book_shop.genre (id, name, ord) VALUES (38, 'Учебные пособия', 380);
INSERT INTO book_shop.genre (id, name, ord) VALUES (39, 'Языковые искусства и дисциплины', 390);
INSERT INTO book_shop.genre (id, name, ord) VALUES (40, 'Комиксы и Графические романы', 400);
INSERT INTO book_shop.genre (id, name, ord) VALUES (41, 'Исполнительское искусство', 410);
INSERT INTO book_shop.genre (id, name, ord) VALUES (42, 'Юмор', 420);
INSERT INTO book_shop.genre (id, name, ord) VALUES (43, 'Политология', 430);
INSERT INTO book_shop.genre (id, name, ord) VALUES (44, 'Технологии и инжиниринг', 440);
INSERT INTO book_shop.genre (id, name, ord) VALUES (45, 'Самопомощь', 450);
INSERT INTO book_shop.genre (id, name, ord) VALUES (46, 'Семья и отношения', 460);
INSERT INTO book_shop.genre (id, name, ord) VALUES (47, 'Фотография', 470);
INSERT INTO book_shop.genre (id, name, ord) VALUES (48, 'Путешествовия', 480);
INSERT INTO book_shop.genre (id, name, ord) VALUES (49, 'Изучение иностранного языка', 490);
INSERT INTO book_shop.genre (id, name, ord) VALUES (50, 'Музыка', 500);
INSERT INTO book_shop.genre (id, name, ord) VALUES (51, 'Бизнес и экономика', 510);
INSERT INTO book_shop.genre (id, name, ord) VALUES (52, 'Геология, Стратиграфия', 520);

INSERT INTO book_shop.genre_lang (genre_id, name) VALUES (0, 'en => "Law"');
INSERT INTO book_shop.genre_lang (genre_id, name) VALUES (1, 'en => "Cooking"');
INSERT INTO book_shop.genre_lang (genre_id, name) VALUES (2, 'en => "Games & Activities"');
INSERT INTO book_shop.genre_lang (genre_id, name) VALUES (3, 'en => "Psychology"');
INSERT INTO book_shop.genre_lang (genre_id, name) VALUES (4, 'en => "History"');
INSERT INTO book_shop.genre_lang (genre_id, name) VALUES (5, 'en => "Juvenile Nonfiction"');
INSERT INTO book_shop.genre_lang (genre_id, name) VALUES (6, 'en => "Chemistry, Inorganic"');
INSERT INTO book_shop.genre_lang (genre_id, name) VALUES (7, 'en => "Algebra"');
INSERT INTO book_shop.genre_lang (genre_id, name) VALUES (8, 'en => "House & Home"');
INSERT INTO book_shop.genre_lang (genre_id, name) VALUES (9, 'en => "Education"');
INSERT INTO book_shop.genre_lang (genre_id, name) VALUES (10, 'en => "Diplomatic relations"');
INSERT INTO book_shop.genre_lang (genre_id, name) VALUES (11, 'en => "Poetry"');
INSERT INTO book_shop.genre_lang (genre_id, name) VALUES (12, 'en => "Electronic books"');
INSERT INTO book_shop.genre_lang (genre_id, name) VALUES (13, 'en => "Architecture"');
INSERT INTO book_shop.genre_lang (genre_id, name) VALUES (14, 'en => "Literary Criticism"');
INSERT INTO book_shop.genre_lang (genre_id, name) VALUES (15, 'en => "Body, Mind & Spirit"');
INSERT INTO book_shop.genre_lang (genre_id, name) VALUES (16, 'en => "Health & Fitness"');
INSERT INTO book_shop.genre_lang (genre_id, name) VALUES (17, 'en => "Young Adult Fiction"');
INSERT INTO book_shop.genre_lang (genre_id, name) VALUES (18, 'en => "Literary Collections"');
INSERT INTO book_shop.genre_lang (genre_id, name) VALUES (19, 'en => "Social Science"');
INSERT INTO book_shop.genre_lang (genre_id, name) VALUES (20, 'en => "Antiques & Collectibles"');
INSERT INTO book_shop.genre_lang (genre_id, name) VALUES (21, 'en => "Diet"');
INSERT INTO book_shop.genre_lang (genre_id, name) VALUES (22, 'en => "Medical"');
INSERT INTO book_shop.genre_lang (genre_id, name) VALUES (23, 'en => "Fiction"');
INSERT INTO book_shop.genre_lang (genre_id, name) VALUES (24, 'en => "Philosophy"');
INSERT INTO book_shop.genre_lang (genre_id, name) VALUES (25, 'en => "Computers"');
INSERT INTO book_shop.genre_lang (genre_id, name) VALUES (26, 'en => "Biography & Autobiography"');
INSERT INTO book_shop.genre_lang (genre_id, name) VALUES (27, 'en => "Art"');
INSERT INTO book_shop.genre_lang (genre_id, name) VALUES (28, 'en => "Corruption"');
INSERT INTO book_shop.genre_lang (genre_id, name) VALUES (29, 'en => "Metals"');
INSERT INTO book_shop.genre_lang (genre_id, name) VALUES (30, 'en => "Science"');
INSERT INTO book_shop.genre_lang (genre_id, name) VALUES (31, 'en => "Mathematics"');
INSERT INTO book_shop.genre_lang (genre_id, name) VALUES (32, 'en => "Juvenile Fiction"');
INSERT INTO book_shop.genre_lang (genre_id, name) VALUES (33, 'en => "Orthogonal polynomials"');
INSERT INTO book_shop.genre_lang (genre_id, name) VALUES (34, 'en => "Sports & Recreation"');
INSERT INTO book_shop.genre_lang (genre_id, name) VALUES (35, 'en => "Nature"');
INSERT INTO book_shop.genre_lang (genre_id, name) VALUES (36, 'en => "Reference"');
INSERT INTO book_shop.genre_lang (genre_id, name) VALUES (37, 'en => "Religion"');
INSERT INTO book_shop.genre_lang (genre_id, name) VALUES (38, 'en => "Study Aids"');
INSERT INTO book_shop.genre_lang (genre_id, name) VALUES (39, 'en => "Language Arts & Disciplines"');
INSERT INTO book_shop.genre_lang (genre_id, name) VALUES (40, 'en => "Comics & Graphic Novels"');
INSERT INTO book_shop.genre_lang (genre_id, name) VALUES (41, 'en => "Performing Arts"');
INSERT INTO book_shop.genre_lang (genre_id, name) VALUES (42, 'en => "Humor"');
INSERT INTO book_shop.genre_lang (genre_id, name) VALUES (43, 'en => "Political Science"');
INSERT INTO book_shop.genre_lang (genre_id, name) VALUES (44, 'en => "Technology & Engineering"');
INSERT INTO book_shop.genre_lang (genre_id, name) VALUES (45, 'en => "Self-Help"');
INSERT INTO book_shop.genre_lang (genre_id, name) VALUES (46, 'en => "Family & Relationships"');
INSERT INTO book_shop.genre_lang (genre_id, name) VALUES (47, 'en => "Photography"');
INSERT INTO book_shop.genre_lang (genre_id, name) VALUES (48, 'en => "Travel"');
INSERT INTO book_shop.genre_lang (genre_id, name) VALUES (49, 'en => "Foreign Language Study"');
INSERT INTO book_shop.genre_lang (genre_id, name) VALUES (50, 'en => "Music"');
INSERT INTO book_shop.genre_lang (genre_id, name) VALUES (51, 'en => "Business & Economics"');
INSERT INTO book_shop.genre_lang (genre_id, name) VALUES (52, 'en => "Geology, Stratigraphic"');
