name: Upload coverage reports to Codecov

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

uses: codecov/codecov-action@v3
  env:
    CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

